app/bloggerspole/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url('signup/', views.signup_account, name='signup_path'),
    url('login/', views.login_account, name='login_path'),
    url('logout/', views.logout_account, name='logout_path'),
]

app/bloggerspole/bloggerspole/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from django.conf.urls.static import static

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blogs/comments/', include('comments.urls')),
    path('blogs/', include('blogs.urls')),
    url('', views.landing, name='landing_path'),
]

app/bloggerspole/blogs/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'blogs'

urlpatterns = [
    url('create/', views.create, name='create_path'),
    url('index/', views.index, name='index_path'),
    path('<int:id_b>/read/', views.read, name='read_path'),
    path('<int:id_b>/update/', views.update, name='update_path'),
    path('<int:id_b>/delete/', views.delete, name='delete_path'),
    path('<int:id_b>/upvote/', views.upvote, name='upvote_path'),
    path('<int:id_b>/downvote/', views.downvote, name='downvote_path'),
]

app/bloggerspole/templates/landing.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>BloggersPole</title>
    </head>
    <body>
        <main>
            <h5>Welcome to<h5>
            <h1>Bloggers-Pole</h1>
            <h3>Blog to Inspire</h3>
            <nav>
                <ul>
                    <a href="{% url 'accounts:login_path' %}"><li>Login<br>For existing users</li></a>
                    <a href="{% url 'accounts:signup_path' %}"><li>Signup<br>Hurry up! Join us today</li></a>
                </ul>
            </nav>
        </main>
    </body>
</html>

app/bloggerspole/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}
            {% endblock %}
        </title>
        <style>
            {% block style %}
            {% endblock %}
        </style>
    </head>
    <body>
        <header>
            <a href="{% url 'blogs:index_path' %}"><h1>Bloggers-Pole</h1></a>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>{{ request.user.username }}</li>
                        <a href="{% url 'accounts:logout_path' %}"><li>Logout</li></a>
                        <a href="{% url 'blogs:create_path' %}"><li>New Blog</li></a>
                    {% else %}
                        <a href="{% url 'accounts:login_path' %}" class="login"><li>Login</li></a>
                        <a href="{% url 'accounts:signup_path' %}" class="signup"><li>Signup</li></a>
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% block body %}
        {% endblock %}
    </body>
</html>