app/bloggerspole/bloggerspole/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from django.conf.urls.static import static

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blogs/comments/', include('comments.urls')),
    path('blogs/', include('blogs.urls')),
    url('', views.landing, name='landing_path'),
]

app/bloggerspole/blogs/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'blogs'

urlpatterns = [
    url('create/', views.create, name='create_path'),
    url('index/', views.index, name='index_path'),
    path('<int:id_b>/read/', views.read, name='read_path'),
    path('<int:id_b>/update/', views.update, name='update_path'),
    path('<int:id_b>/delete/', views.delete, name='delete_path'),
    path('<int:id_b>/upvote/', views.upvote, name='upvote_path'),
    path('<int:id_b>/downvote/', views.downvote, name='downvote_path'),
]

app/bloggerspole/comments/urls.py
from django.conf.urls import url
from django.urls.conf import path
from . import views

app_name = 'comments'

urlpatterns = [
    path('<int:id_b>/create/', views.create, name='create_path'),
    path('<int:id_c>/delete', views.delete, name='delete_path'),
]

app/bloggerspole/blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class Blog(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100) 
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    thumb = models.ImageField(default=None, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    upvotes = models.IntegerField(default=0)
    liked_by = models.ManyToManyField(User, related_name='likes')
    disliked_by = models.ManyToManyField(User, related_name='dislikes')
    downvotes = models.IntegerField(default=0)
    def __str__(self):
        return self.title
    def snippet(self):
        return self.body[:50] + '...'

app/bloggerspole/blogs/forms.py
from django import forms
from . import models

class NewBlogForm(forms.ModelForm):
    class Meta:
        model = models.Blog
        fields = [
            'title',
            'body',
            'thumb',
        ]

app/bloggerspole/blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import NewBlogForm
from .models import Blog
from comments.models import Comment
from comments.forms import NewCommentForm

@login_required(login_url='accounts:login_path')
def create(request):
    if request.method == 'POST':
        form = NewBlogForm(request.POST, request.FILES)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.author = request.user
            blog.save()
            return redirect('blogs:read_path', id_b=blog.id)
    else:
        form = NewBlogForm()
    return render(request, 'blogs/create.html', { 'form': form })

def index(request):
    blogs = Blog.objects.all().order_by('created_on')
    return render(request, 'blogs/index.html', {
        'blogs': blogs,
    })

@login_required(login_url='accounts:login_path')
def read(request, id_b):
    blog = Blog.objects.get(id=id_b)
    comments = Comment.objects.filter(blog=blog).order_by('created_on').reverse()
    form = NewCommentForm()
    return render(request, 'blogs/read.html', {
        'blog': blog,
        'comments': comments,
        'form': form,
    })

@login_required(login_url='accounts:login_path')
def update(request, id_b):
    blog = Blog.objects.get(id=id_b)
    if request.user != blog.author:
        raise PermissionError
    if request.method == 'POST':
        form = NewBlogForm(request.POST, request.FILES)
        if form.is_valid():
            upt_blog = form.save(commit=False)
            blog.title = upt_blog.title
            blog.body = upt_blog.body
            blog.thumb = upt_blog.thumb
            blog.save()
            return redirect('blogs:read_path', id_b=id_b)
    else:
        form = NewBlogForm(instance=blog)
    return render(request, 'blogs/update.html', { 'form': form, 'blog': blog })


@login_required(login_url='accounts:login_path')
def delete(request, id_b):
    blog = Blog.objects.get(id=id_b)
    user = request.user
    if blog.author == user:
        blog.delete()
        return redirect('blogs:index_path')
    else:
        raise PermissionError

@login_required(login_url='accounts:login_path')
def upvote(request, id_b):
    user = request.user
    blog = Blog.objects.get(id=id_b)
    if blog not in user.likes.all():
        if blog in user.dislikes.all():
            user.dislikes.remove(blog)
            blog.downvotes = blog.downvotes - 1
        user.likes.add(blog)
        blog.upvotes = blog.upvotes + 1
    else:
        user.likes.remove(blog)
        blog.upvotes = blog.upvotes - 1
    blog.save()
    return redirect('blogs:read_path', id_b=id_b)

@login_required(login_url='accounts:login_path')
def downvote(request, id_b):
    user = request.user
    blog = Blog.objects.get(id=id_b)
    if blog not in user.dislikes.all():
        if blog in user.likes.all():
            user.likes.remove(blog)
            blog.upvotes = blog.upvotes - 1
        user.dislikes.add(blog)
        blog.downvotes = blog.downvotes + 1
    else:
        user.dislikes.remove(blog)
        blog.downvotes = blog.downvotes - 1
    blog.save()
    return redirect('blogs:read_path', id_b=id_b)

app/bloggerspole/blogs/templates/blogs/create.html
{% extends 'layout.html' %}

{% block title %}
    BloggersPole | New Blog
{% endblock %}

{% block body %}
    <h2>New Blog</h2>
    <form action="{% url 'blogs:create_path' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- <table>
            {% if form.errors %}
                <tr>
                    {{ form.non_field_errors }}
                </tr>
            {% endif %}
            {% for field in form.visible_fields %}
                <tr>
                    <th>{{ field.label_tag }}</th>
                    <td>
                        {{ field }}
                        {% if field.help_text %}
                            {{ field.help_text }}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table> -->
        {{ form }}
        <input type="submit" value="Publish">
    </form>
{% endblock %}

app/bloggerspole/blogs/templates/blogs/index.html
{% extends 'layout.html' %}

{% block title %}
    BloggersPole
{% endblock %}

{% block style %}
    article {
        border: 1px solid black;
        width: 500px;
        margin: 20px;
    }
    img {
        width: 300px;
    }
{% endblock %}

{% block body %}
    {% if blogs %}
        {% for blog in blogs %}
            <a href="{% url 'blogs:read_path' id_b=blog.id %}">
                <article>
                    <header>
                        <h3>{{ blog.title }}</h3>
                        <h4>by {{ blog.author.username }}</h4>
                        <ul>
                            <li>Upvotes: {{ blog.upvotes }}</li>
                            <li>Downvotes: {{ blog.downvotes }}</li>
                        </ul>
                    </header>
                    {% if blog.thumb %}
                        <figure>
                            <img src="{{ blog.thumb.url }}" alt="{{ blog.title }}">
                        </figure>
                    {% endif %}
                    <main>
                        <p>{{ blog.snippet }}</p>
                    </main>
                </article>
            </a>
        {% endfor %}
    {% endif %}
{% endblock %}

app/bloggerspole/blogs/templates/blogs/read.html
{% extends 'layout.html' %}

{% block title %}
    BloggersPole | {{ blog.title }}
{% endblock %}

{% block body %}
    <article>
        <header>
            <h2>{{ blog.title }}</h2>
            <h3>by {{ blog.author.username }}</h3>
            <ul>
                <li><a href="{% url 'blogs:upvote_path' id_b=blog.id %}">Upvote</a><br>{{ blog.upvotes }}</li>
                <li><a href="{% url 'blogs:downvote_path' id_b=blog.id %}">Downvote</a><br>{{ blog.downvotes }}</li>
            </ul>
        </header>
        {% if request.user == blog.author %}
            <nav>
                <ul>
                    <a href="{% url 'blogs:update_path' id_b=blog.id %}"><li>Edit</li></a>
                    <a href="{% url 'blogs:delete_path' id_b=blog.id %}"><li>Delete</li></a>
                </ul>
            </nav>
        {% endif %}
        {% if blog.thumb %}
            <figure>
                <img src="{{ blog.thumb.url }}">
            </figure>
        {% endif %}
        <main>
            <p>{{ blog.snippet }}</p>
        </main>
    </article>
    <section>
        <h3>Comments</h3>
        <form action="{% url 'comments:create_path' id_b=blog.id %}" method="post">
            {% csrf_token %}
            <table>
                {% if form.errors %}
                    <tr>
                        {{ form.non_field_errors }}
                    </tr>
                {% endif %}
                {% for field in form.visible_fields %}
                    <tr>
                        <th>{{ field.label_tag }}</th>
                        <td>
                            {{ field }}
                            {% if field.help_text %}
                                {{ field.help_text }}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </table>
            <input type="submit" value="Comment">
        </form>
        {% for comment in comments %}
            <ul>
                <li>
                    {{ comment.body }}<br>
                    by {{ comment.author.username }}<br>
                    {{ comment.created_on }}<br>
                    {% if request.user == comment.author %}
                        <a href="{% url 'comments:delete_path' id_c=comment.id %}">Delete</a>
                    {% endif %}
                </li>
            </ul>
        {% endfor %}
    </section>
{% endblock %}

app/bloggerspole/blogs/templates/blogs/update.html
{% extends 'layout.html' %}

{% block title %}
    BloggersPole | Edit Blog
{% endblock %}

{% block body %}
    <h2>{{ blog.title }}</h2>
    <form action="{% url 'blogs:update_path' id_b=blog.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {% if form.errors %}
                <tr>
                    {{ form.non_field_errors }}
                </tr>
            {% endif %}
            {% for field in form.visible_fields %}
                <tr>
                    <th>{{ field.label_tag }}</th>
                    <td>
                        {{ field }}
                        {% if field.help_text %}
                            {{ field.help_text }}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
        <input type="submit" value="Confirm">
    </form>
{% endblock %}